# Generated by Django 2.1.7 on 2019-03-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='students_home',
            field=models.OneToOneField(null=True, on_delete=None, to='Login.Student'),
        ),
    ]
