# Generated by Django 2.1.7 on 2019-03-16 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer_name', models.CharField(max_length=50, verbose_name='回答者')),
                ('Answer_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='回答时间')),
                ('Answer', models.CharField(max_length=200, verbose_name='回答内容')),
            ],
            options={
                'verbose_name': '回答内容',
                'verbose_name_plural': '回答内容',
                'db_table': 'Answer',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=200, verbose_name='问题内容')),
            ],
            options={
                'verbose_name': '问题内容',
                'verbose_name_plural': '问题内容',
                'db_table': 'Questions',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
