# Generated by Django 2.1.7 on 2019-03-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20190317_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='students_home',
        ),
    ]
