# Generated by Django 2.1.7 on 2019-03-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='hw_chengji',
            field=models.OneToOneField(null=True, on_delete=None, to='Login.Chengji'),
        ),
    ]
