# Generated by Django 2.1.7 on 2019-03-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='stu_name',
            field=models.ManyToManyField(blank=True, null=True, to='Main.Student', verbose_name='学生'),
        ),
    ]
