# Generated by Django 2.1.7 on 2019-03-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_uploadname',
            field=models.OneToOneField(null=True, on_delete=None, to='Main.Student', verbose_name='上传用户'),
        ),
    ]
