# Generated by Django 2.1.7 on 2019-03-21 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_abc_abc_stu'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Main.abc'),
        ),
    ]
