# Generated by Django 2.1.7 on 2019-03-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_student_stu_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='abc_stu',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_grade',
        ),
    ]
