# Generated by Django 2.1.7 on 2019-03-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20190323_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_grade',
            field=models.OneToOneField(blank=True, null=True, on_delete=None, to='Main.abc'),
        ),
    ]
