# Generated by Django 2.1.7 on 2019-03-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_answer_answer_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
