# Generated by Django 2.1.7 on 2019-03-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_abc_abc_stu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='abc_stu',
        ),
        migrations.AddField(
            model_name='abc',
            name='abc_stu',
            field=models.ManyToManyField(blank=True, null=True, to='Main.Student'),
        ),
    ]
