# Generated by Django 2.1.7 on 2019-03-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20190321_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='abc_stu',
            field=models.ManyToManyField(null=True, to='Main.Student'),
        ),
    ]
