# Generated by Django 2.1.7 on 2019-03-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20190321_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='abc_stu',
        ),
        migrations.AddField(
            model_name='student',
            name='abc_stu',
            field=models.ManyToManyField(null=True, to='Main.abc'),
        ),
    ]
