# Generated by Django 2.1.7 on 2019-03-21 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20190321_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitselectgrade',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='submitselectgrade',
            name='major',
        ),
        migrations.AddField(
            model_name='submitselectgrade',
            name='chioces',
            field=models.ForeignKey(null=True, on_delete=None, to='Main.Student'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.abc', verbose_name='作业的班级'),
        ),
    ]
