# Generated by Django 2.1.7 on 2019-03-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20190321_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='昵称'),
        ),
    ]
