# Generated by Django 2.1.7 on 2019-03-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20190321_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_grade',
            field=models.ManyToManyField(blank=True, to='Main.abc', verbose_name='班级'),
        ),
    ]
