# Generated by Django 2.1.7 on 2019-03-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20190321_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='abc_stu',
            field=models.ManyToManyField(blank=True, null=True, to='Main.abc'),
        ),
    ]
