# Generated by Django 2.1.7 on 2019-03-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20190321_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_teacher',
        ),
    ]
